from minos.common.exceptions import MinosException


class MinosNetworkException(MinosException):
    pass
